---
metadata:
  - name: description
    content: The Isoptera Species File is a taxonomic, nomenclatural, and bibliographic database of the termites of the world, including all extant and fossil taxa.
  - name: keywords
    content: taxonomy, species, Species File Group, Isoptera, termites, taxonpages, Isoptera Species File
  - name: robots
    content: follow
