---
  project_name: "Isoptera Species File"
  project_citation: "Isoptera Species File"
  project_authors: "Hopkins, H."
  project_url: "https://isoptera.speciesfile.org" 
  focal_taxon: "isoptera"
  focal_taxon_common_name: "termites"
  contact_email: "cockroachdoc@gmail.com"
